http:
  middlewares:

    authelia:
      forwardAuth:
        address: "http://authelia:9091/api/verify?rd=https://login.localhost/"
        trustForwardHeader: true
        authResponseHeaders:
          - "Remote-User"
          - "Remote-Groups"

    secured:
      chain:
        middlewares:
          - internal-network
          - redirect-to-https
          - auth-traefik.users
          - security-headers

    redirect-to-https:
      redirectScheme:
        scheme: https
        permanent: true
        port: 443

    internal-network:
      ipWhiteList:
        sourceRange:
          - "127.0.0.1/24" # localhost
          - "172.0.0.1/8" # all docker containers

    small-rate-limit:
      rateLimit:
        average: 10
        burst: 10

    big-rate-limit:
      rateLimit:
        average: 100
        burst: 50

    auth-users:
      basicAuth:
        removeHeader: true
        realm: basic
        usersFile: "/configuration/traefik.users"

    security-headers:
      headers:
        frameDeny: true
        sslRedirect: true
        contentTypeNosniff: true
        browserXssFilter: true
