http:
  middlewares:

    secured:
      chain:
        middlewares:
# Remove comments when you want to accept requests only from the inside
# Probably would be the best to keep it as first middleware
#          - internal-network
          - redirect-to-https
          - security-headers
          - users
#          - authelia # uncomment this if you are not afraid of 1GB of RAM missing..

    media-secured:
      chain:
        middlewares:
          - redirect-to-https
          - security-headers
          - media-users

    no-login-secured:
      chain:
        middlewares:
          - redirect-to-https
          - security-headers
          - big-rate-limit

    users:
      basicAuth:
        removeHeader: true
        realm: "Only admins"
        usersFile: "/configuration/dynamic/traefik.users.txt"
    
    media-users:
      basicAuth:
        removeHeader: true
        realm: "Media users"
        usersFile: "/configuration/dynamic/traefik.media.txt"

    redirect-to-https:
      redirectScheme:
        scheme: https
        permanent: true
        port: 443

    internal-network:
      ipWhiteList:
        sourceRange:
          - "127.0.0.1/24" # localhost
          - "172.0.0.1/8" # all docker containers

    small-rate-limit:
      rateLimit:
        average: 10
        burst: 10

    big-rate-limit:
      rateLimit:
        average: 50
        burst: 50

    security-headers:
      headers:
        frameDeny: true
        sslRedirect: true
        contentTypeNosniff: true
        browserXssFilter: true
        customResponseHeaders:
          X-Robots-Tag: "noindex,nofollow,nosnippet,noarchive,notranslate,noimageindex"

# uncomment if you would like to authenticate your users with authelia
#    authelia:
#      forwardAuth:
#        address: "http://authelia:9091/api/verify?rd=https://login.house.swarm/"
#        trustForwardHeader: true
#        authResponseHeaders:
#          - "Remote-User"
#          - "Remote-Groups"
