http:
  middlewares:

    secured:
      chain:
        middlewares:
          - internal-network # comment this out when you want to accept requests from the outside
          - redirect-to-https
          - security-headers
          - users
#          - authelia # uncomment this if you are not afraid of 1GB of RAM missing..

    users:
      basicAuth:
        realm: HouseSwarm
        usersFile: "/configuration/dynamic/traefik.users.txt"


    redirect-to-https:
      redirectScheme:
        scheme: https
        permanent: true
        port: 443

    internal-network:
      ipWhiteList:
        sourceRange:
          - "127.0.0.1/24" # localhost
          - "172.0.0.1/8" # all docker containers

    small-rate-limit:
      rateLimit:
        average: 10
        burst: 10

    big-rate-limit:
      rateLimit:
        average: 100
        burst: 50

    security-headers:
      headers:
        frameDeny: true
        sslRedirect: true
        contentTypeNosniff: true
        browserXssFilter: true

# uncomment if you would like to authenticate your users with authelio
#    authelia:
#      forwardAuth:
#        address: "http://authelia:9091/api/verify?rd=https://login.house.swarm/"
#        trustForwardHeader: true
#        authResponseHeaders:
#          - "Remote-User"
#          - "Remote-Groups"
