global:
  scrape_interval:     30s
  evaluation_interval: 30s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']

  - job_name: traefik
    static_configs:
      - targets: ['traefik:8082']

  - job_name: node_exporter
    static_configs:
      - targets: ['node_exporter:9100']

  # will check periodically if given URLs are up.
  # - job_name: blackbox
  #   scrape_interval: 15m
  #   metrics_path: /probe
  #   params:
  #     module: [http_get]
  #   static_configs:
  #     - targets:
  #         - https://www.up.pl/
  #         - https://www.google.pl/
  #         - https://www.youtube.com/
  #   relabel_configs:
  #     - source_labels: [__address__]
  #       target_label: __param_target
  #     - source_labels: [__param_target]
  #       target_label: instance
  #     - target_label: __address__
  #       replacement: blackbox_exporter:9115
