global:
  scrape_interval:     30s
  evaluation_interval: 30s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']
  - job_name: traefik
    static_configs:
      - targets: ['traefik:8082']
  - job_name: docker_manager
    static_configs:
      - targets: ['docker_exporter:9417']
