entryPoints:
  https:
    address: ":443"
  http:
    address: ":80"
  metrics:
    address: ":8082"
  dns53tcp:
    address: ":53/tcp"
  dns53udp:
    address: ":53/udp"

global:
  checkNewVersion: true

providers:
  file:
    watch: true
    directory: /configuration/dynamic
  docker:
    watch: true
    network: traefik-public
    exposedByDefault: false

metrics:
  prometheus:
    addEntryPointsLabels: true
    addServicesLabels: true
    manualRouting: false
    entryPoint: metrics

log: {}

api:
  dashboard: true

serversTransport:
  insecureSkipVerify: true
  rootCAs:
    - /certificates/ca.crt

tls:
  options:
    default:
      sniStrict: false

  default:
    minVersion: VersionTLS13

  stores:
    default:
      defaultCertificate:
        certFile: /certificates/server.crt
        keyFile: /certificates/server.key
