name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Lint Traefik
        run: docker-compose -f traefik.yml config

      - name: Lint Monitoring
        run: docker-compose -f traefik.yml -f monitoring.yml config

      - name: Lint PiHole
        run: docker-compose -f traefik.yml -f pihole.yml config
